[package]
name = "sdl2-template"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-getters = "0.4.0"
glam = "0.28.0"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["image"]
